// <auto-generated />
using ConsultorioDeSeguros.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultorioDeSeguros.Infrastructure.Migrations
{
    [DbContext(typeof(SegurosContexto))]
    [Migration("20220703150335_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ConsultorioDeSeguros.Domain.Asegurados.Models.AseguradoModel", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("cedula");

                    b.Property<byte>("Edad")
                        .HasColumnType("tinyint")
                        .HasColumnName("edad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("telefono");

                    b.HasKey("Cedula")
                        .HasName("pk_asegurado");

                    b.ToTable("t_asegurado", "dbo");

                    b.HasData(
                        new
                        {
                            Cedula = "0925613556",
                            Edad = (byte)25,
                            Nombre = "Christian Franco",
                            Telefono = "+593985749632"
                        },
                        new
                        {
                            Cedula = "1756359625",
                            Edad = (byte)32,
                            Nombre = "Ed Sheeran",
                            Telefono = "0985369514"
                        });
                });

            modelBuilder.Entity("ConsultorioDeSeguros.Domain.Seguros.Models.SeguroAseguradoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AseguradoCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("cedula");

                    b.Property<int>("SeguroCodigo")
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.HasKey("Id")
                        .HasName("pk_sseguro_asegurado");

                    b.HasIndex("AseguradoCedula");

                    b.HasIndex("SeguroCodigo");

                    b.ToTable("t_seguro_asegurado", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AseguradoCedula = "1756359625",
                            SeguroCodigo = 1
                        },
                        new
                        {
                            Id = 2,
                            AseguradoCedula = "1756359625",
                            SeguroCodigo = 2
                        },
                        new
                        {
                            Id = 3,
                            AseguradoCedula = "1756359625",
                            SeguroCodigo = 3
                        },
                        new
                        {
                            Id = 4,
                            AseguradoCedula = "0925613556",
                            SeguroCodigo = 1
                        });
                });

            modelBuilder.Entity("ConsultorioDeSeguros.Domain.Seguros.Models.SeguroModel", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Prima")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("prima");

                    b.Property<decimal>("SumaAsegurada")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("SumaAsegurada");

                    b.HasKey("Codigo")
                        .HasName("pk_seguro");

                    b.ToTable("t_seguro", "dbo");

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Nombre = "Vida",
                            Prima = 20.00m,
                            SumaAsegurada = 200.00m
                        },
                        new
                        {
                            Codigo = 2,
                            Nombre = "Salud",
                            Prima = 20.00m,
                            SumaAsegurada = 200.00m
                        },
                        new
                        {
                            Codigo = 3,
                            Nombre = "Vehícular",
                            Prima = 20.00m,
                            SumaAsegurada = 200.00m
                        });
                });

            modelBuilder.Entity("ConsultorioDeSeguros.Domain.Seguros.Models.SeguroAseguradoModel", b =>
                {
                    b.HasOne("ConsultorioDeSeguros.Domain.Asegurados.Models.AseguradoModel", "Asegurado")
                        .WithMany("Seguros")
                        .HasForeignKey("AseguradoCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConsultorioDeSeguros.Domain.Seguros.Models.SeguroModel", "Seguro")
                        .WithMany("Asegurados")
                        .HasForeignKey("SeguroCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asegurado");

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("ConsultorioDeSeguros.Domain.Asegurados.Models.AseguradoModel", b =>
                {
                    b.Navigation("Seguros");
                });

            modelBuilder.Entity("ConsultorioDeSeguros.Domain.Seguros.Models.SeguroModel", b =>
                {
                    b.Navigation("Asegurados");
                });
#pragma warning restore 612, 618
        }
    }
}
